# Generated by Django 5.1.1 on 2024-10-01 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите место, где вы занимаетесь",
                        max_length=100,
                        verbose_name="Место",
                    ),
                ),
                (
                    "do_at",
                    models.DateTimeField(
                        help_text="Укажите дату и время выполнения",
                        verbose_name="Дата и время выполнения",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие, которое вы выполняете",
                        max_length=100,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_enjoyable",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите, приятную ли привычку вы выполняете",
                        verbose_name="Приятная ли привычка",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Укажите периодичность выполнения привычки в днях",
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение за выполнение привычки",
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        help_text="Укажите продолжительность выполнения действия в секундах",
                        verbose_name="Продолжительность",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите, публичная ли привычка",
                        verbose_name="Публичная ли привычка",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
